set serveroutput on;

CREATE OR REPLACE PROCEDURE CONSULTARPENSUM 
(
  CODIGOCARRERA IN NUMBER 
  , cursor_ OUT SYS_REFCURSOR
) AS 
BEGIN
  DECLARE
  validarCarrera NUMBER := 0; 
  
  BEGIN
    SELECT COUNT(*) INTO validarCarrera FROM CARRERA 
    WHERE CARRERA = CODIGOCARRERA;
    
    IF validarCarrera > 0 THEN
        
        OPEN cursor_ FOR
        SELECT c.CODIGO
        , c.NOMBRE
        , CASE p.OBLIGATORIEDAD WHEN '1' THEN 'OBLIGATORIO' ELSE 'NO OBLIGATORIO' END AS OBLIGATORIO
        , p.NUMCREDITOS AS CREDITOS
        , p.CREDPRERREQ AS CREDITOSNECESARIOS
        FROM PENSUM p
        INNER JOIN CURSO c ON p.CURSO_CODIGO = c.CODIGO
        WHERE p.PLAN_CARRERA_CARRERA = CODIGOCARRERA;
        
    ELSE 
        DBMS_OUTPUT.PUT_LINE('NO EXISTE LA CARRERA');
    END IF;
  END;
  
END CONSULTARPENSUM;