set serveroutput on;

CREATE OR REPLACE PROCEDURE CONSULTARESTUDIANTE 
(
  CCARNET IN NUMBER 
  , cursor_ OUT SYS_REFCURSOR
) AS 
BEGIN
  DECLARE
  validarEstudiante NUMBER := 0; 
  
  BEGIN
    SELECT COUNT(*) INTO validarEstudiante FROM ESTUDIANTE 
    WHERE CARNET = CCARNET;
    
    IF validarEstudiante > 0 THEN
        
        OPEN cursor_ FOR
        SELECT E.CARNET
        , E.NOMBRE || ' ' || E.APELLIDO AS NOMBRECOMPLETO
        , E.FECHANACIMIENTO
        , E.CORREO
        , E.TELEFONO
        , E.DIRECCION
        , E.DPI
        , C.NOMBRE
        , NVL(S.NUMCREDITOS, 0) AS NUMCREDITOS
        FROM ESTUDIANTE E
        INNER JOIN INSCRITO I ON E.CARNET = I.ESTUDIANTE_CARNET
        INNER JOIN CARRERA C ON I.CARRERA_CARRERA = C.CARRERA
        LEFT OUTER JOIN (
            SELECT E1.CARNET, SUM(P.NUMCREDITOS) AS NUMCREDITOS FROM ESTUDIANTE E1 
            INNER JOIN ASIGNACION A ON E1.CARNET = A.ESTUDIANTE_CARNET 
            INNER JOIN CURSO CU ON A.SECCION_CURSO_CODIGO = CU.CODIGO
            INNER JOIN PENSUM P ON CU.CODIGO = P.CURSO_CODIGO
            WHERE (A.ZONA + A.NOTA) > P.NOTAAPROBACION
            GROUP BY E1.CARNET
        ) S ON E.CARNET = S.CARNET
        WHERE E.CARNET = CCARNET;
        
    ELSE 
        DBMS_OUTPUT.PUT_LINE('NO EXISTE EL ESTUDIANTE');
    END IF;
    
  END;
  
END CONSULTARESTUDIANTE;