set serveroutput on;

CREATE OR REPLACE PROCEDURE CONSULTARHORARIO 
(
  CARNET IN NUMBER 
, CICLO IN VARCHAR2 
, ANIO IN NUMBER 
, cursor_ OUT SYS_REFCURSOR
) AS 
BEGIN
  DECLARE 
validarCarnet NUMBER := 0; 

BEGIN
    SELECT COUNT(*) INTO validarCarnet FROM ESTUDIANTE 
    WHERE CARNET = CARNET;
    
    IF validarCarnet > 0 THEN
        IF CICLO = '1S' OR CICLO = '2S' OR CICLO = 'VJ' OR CICLO = 'VD' THEN
        
            OPEN cursor_ FOR
            SELECT C.NOMBRE 
            , A.SECCION_SECCION AS SECCION
            , D.NOMBRE AS DIA
            , H.PERIODO_PERIODO AS PERIODO
            , H.SALON_EDIFICIO || ' , ' || H.SALON_SALON AS LUGAR
            FROM ASIGNACION A
            INNER JOIN HORARIO H ON A.SECCION_SECCION = H.SECCION_SECCION 
            AND A.SECCION_ANIO = H.SECCION_ANIO 
            AND A.SECCION_CURSO_CODIGO = H.SECCION_CURSO_CODIGO
            INNER JOIN ESTUDIANTE E ON A.ESTUDIANTE_CARNET = E.CARNET
            INNER JOIN CURSO C ON A.SECCION_CURSO_CODIGO = C.CODIGO
            INNER JOIN DIA D ON H.DIA_DIA = D.DIA
            WHERE A.SECCION_CICLO = CICLO AND A.SECCION_ANIO = ANIO AND E.CARNET = CARNET;

        ELSE
            DBMS_OUTPUT.PUT_LINE('VALIDAR EL CICLO');
        END IF;
    ELSE 
        DBMS_OUTPUT.PUT_LINE('VALIDAR EL ESTUDIANTE');
    END IF;
   
END;
END CONSULTARHORARIO;