CREATE OR REPLACE TRIGGER TRCATEDRATICO 
AFTER DELETE OR INSERT OR UPDATE ON CATEDRATICO
BEGIN
  IF INSERTING THEN
      INSERT INTO BITACORA(FECHA, DESCRIPCION, TIPO)VALUES(SYSDATE, 'Se ha realizado una acción en la tabla CATEDRATICO', 'INSERT');
  END IF;
  
  IF UPDATING THEN
      INSERT INTO BITACORA(FECHA, DESCRIPCION, TIPO)VALUES(SYSDATE, 'Se ha realizado una acción en la tabla CATEDRATICO', 'UPDATE');
  END IF;
  
  IF DELETING THEN
      INSERT INTO BITACORA(FECHA, DESCRIPCION, TIPO)VALUES(SYSDATE, 'Se ha realizado una acción en la tabla CATEDRATICO', 'DELETE');
  END IF;
  
END;