CREATE OR REPLACE TRIGGER TRESTUDIANTE 
AFTER DELETE OR INSERT OR UPDATE ON ESTUDIANTE
BEGIN
  IF INSERTING THEN
      INSERT INTO BITACORA(FECHA, DESCRIPCION, TIPO)VALUES(SYSDATE, 'Se ha realizado una acción en la tabla ESTUDIANTE', 'INSERT');
  END IF;
  
  IF UPDATING THEN
      INSERT INTO BITACORA(FECHA, DESCRIPCION, TIPO)VALUES(SYSDATE, 'Se ha realizado una acción en la tabla ESTUDIANTE', 'UPDATE');
  END IF;
  
  IF DELETING THEN
      INSERT INTO BITACORA(FECHA, DESCRIPCION, TIPO)VALUES(SYSDATE, 'Se ha realizado una acción en la tabla ESTUDIANTE', 'DELETE');
  END IF;
  
END;