CREATE OR REPLACE TRIGGER TRPRERREQ
AFTER DELETE OR INSERT OR UPDATE ON PRERREQ
BEGIN
  IF INSERTING THEN
      INSERT INTO BITACORA(FECHA, DESCRIPCION, TIPO)VALUES(SYSDATE, 'Se ha realizado una acción en la tabla PRERREQ', 'INSERT');
  END IF;
  
  IF UPDATING THEN
      INSERT INTO BITACORA(FECHA, DESCRIPCION, TIPO)VALUES(SYSDATE, 'Se ha realizado una acción en la tabla PRERREQ', 'UPDATE');
  END IF;
  
  IF DELETING THEN
      INSERT INTO BITACORA(FECHA, DESCRIPCION, TIPO)VALUES(SYSDATE, 'Se ha realizado una acción en la tabla PRERREQ', 'DELETE');
  END IF;
  
END;