CREATE OR REPLACE PROCEDURE DESASIGNARCURSO 
(
  CODIGOSECCION IN NUMBER 
, CARNET IN NUMBER 
) AS 
BEGIN
  DECLARE
  validarAsignacion NUMBER := 0; 
  
   BEGIN
        SELECT COUNT(*) INTO validarAsignacion FROM ASIGNACION 
        WHERE ESTUDIANTE_CARNET = CARNET AND SECCION_SECCION = CODIGOSECCION;
        
        IF validarAsignacion > 0 THEN
            DELETE ASIGNACION
            WHERE ESTUDIANTE_CARNET = CARNET AND SECCION_SECCION = CODIGOSECCION;
            
            DBMS_OUTPUT.PUT_LINE('SE DESASIGNO EL ESTUDIANTE');
        ELSE
            DBMS_OUTPUT.PUT_LINE('NO EXISTE LA ASIGNACION');
        END IF;
        
    END;
  
END DESASIGNARCURSO;