set serveroutput on;

CREATE OR REPLACE PROCEDURE INGRESARNOTA 
(
  CODIGOSECCION IN NUMBER 
, CARNET IN NUMBER 
, ZONA IN NUMBER 
, FINAL IN NUMBER 
) AS 
BEGIN
  DECLARE
  validarAsignacion NUMBER := 0; 
  
   BEGIN
        SELECT COUNT(*) INTO validarAsignacion FROM ASIGNACION 
        WHERE ESTUDIANTE_CARNET = CARNET AND SECCION_SECCION = CODIGOSECCION;
        
        IF validarAsignacion > 0 THEN
            UPDATE ASIGNACION
            SET ZONA = FLOOR(ZONA), NOTA = FLOOR(FINAL)
            WHERE ESTUDIANTE_CARNET = CARNET AND SECCION_SECCION = CODIGOSECCION;
            
            DBMS_OUTPUT.PUT_LINE('SE ASIGNO LA NOTA');
        ELSE
            DBMS_OUTPUT.PUT_LINE('NO EXISTE LA ASIGNACION');
        END IF;
        
    END;
  
END INGRESARNOTA;